Sleep between Aliyun push attempts

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -75,7 +75,7 @@ jobs:
                   echo "Pushing tag $CIRCLE_TAG"
                   make docker-push-all ALL_ARCH="$ALL_ARCH" ALL_DOCKER_BUILD="$ALL_DOCKER_BUILD" TAG="$CIRCLE_TAG" REGISTRY=$REGISTRY_CHINA
                 fi
-              ) || { echo "Failed attempt ${n}"; continue; }
+              ) || { echo "Failed attempt ${n}"; sleep 30; continue; }
 
               echo "Succeeded in attempt ${n}"
               exit 0
